import { z } from "zod";

export const ChartAnalysisSchema = z.object({
  symbol: z.string().min(1).max(32),
  market: z.enum(["forex", "crypto", "commodity", "index", "unknown"]),
  timeframe: z.string().min(1).max(16),
  bias: z.enum(["bullish", "bearish", "neutral"]),
  confidence: z.coerce.number().min(0).max(100),
  trend: z.string().min(1).max(280),
  score: z.coerce.number().min(0).max(100),
  patterns: z.array(z.string().max(80)).max(8),
  support: z.array(z.coerce.number()).max(6),
  resistance: z.array(z.coerce.number()).max(6),
  currentPrice: z.coerce.number(),
  setup: z.object({
    direction: z.enum(["long", "short", "wait"]),
    entryMin: z.coerce.number(),
    entryMax: z.coerce.number(),
    stopLoss: z.coerce.number(),
    takeProfits: z.array(z.coerce.number()).max(4),
    riskReward: z.coerce.number(),
    invalidation: z.string().max(400),
  }),
  rationale: z.string().min(1).max(1800),
  risks: z.array(z.string().max(240)).max(6),
  sessionNotes: z.string().max(400),
});

export const ANALYSIS_JSON_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    symbol: { type: "string" },
    market: {
      type: "string",
      enum: ["forex", "crypto", "commodity", "index", "unknown"],
    },
    timeframe: { type: "string" },
    bias: { type: "string", enum: ["bullish", "bearish", "neutral"] },
    confidence: { type: "number" },
    trend: { type: "string" },
    score: { type: "number" },
    patterns: { type: "array", items: { type: "string" } },
    support: { type: "array", items: { type: "number" } },
    resistance: { type: "array", items: { type: "number" } },
    currentPrice: { type: "number" },
    setup: {
      type: "object",
      additionalProperties: false,
      properties: {
        direction: { type: "string", enum: ["long", "short", "wait"] },
        entryMin: { type: "number" },
        entryMax: { type: "number" },
        stopLoss: { type: "number" },
        takeProfits: { type: "array", items: { type: "number" } },
        riskReward: { type: "number" },
        invalidation: { type: "string" },
      },
      required: [
        "direction",
        "entryMin",
        "entryMax",
        "stopLoss",
        "takeProfits",
        "riskReward",
        "invalidation",
      ],
    },
    rationale: { type: "string" },
    risks: { type: "array", items: { type: "string" } },
    sessionNotes: { type: "string" },
  },
  required: [
    "symbol",
    "market",
    "timeframe",
    "bias",
    "confidence",
    "trend",
    "score",
    "patterns",
    "support",
    "resistance",
    "currentPrice",
    "setup",
    "rationale",
    "risks",
    "sessionNotes",
  ],
} as const;
